package com.github.heikyudev.maestrocervecero.persistence.entity.usuario;

/**
 * Permisos granulares de negocio, agrupados por módulo del ERP (insumos, recetas,
 * producción, compras, etc.). Se usan como {@code GrantedAuthority} sin prefijo
 * (a diferencia de {@link Rol}, que se expone con el prefijo {@code ROLE_}), por lo que se
 * validan en código con {@code @PreAuthorize("hasAuthority('INSUMO_CREAR')")} y no con
 * {@code hasRole(...)}. Cada {@link Rol} define qué subconjunto de estos permisos posee.
 */
public enum Permiso {
    // INSUMOS
    INSUMO_CREAR,
    INSUMO_MODIFICAR,
    INSUMO_ELIMINAR,
    INSUMO_CONSULTAR,
    // EQUIPAMIENTOS
    EQUIPAMIENTO_CREAR,
    EQUIPAMIENTO_MODIFICAR,
    EQUIPAMIENTO_ELIMINAR,
    EQUIPAMIENTO_CONSULTAR,
    //RECETA
    RECETA_CREAR,
    RECETA_MODIFICAR,
    RECETA_ELIMINAR,
    RECETA_CONSULTAR,

    ETAPA_CONTROL_CREAR,
    ETAPA_CONTROL_MODIFICAR,
    ETAPA_CONTROL_ELIMINAR,
    ETAPA_CONTROL_CONSULTAR,

    PARAMETRO_CONTROL_CREAR,
    PARAMETRO_CONTROL_MODIFICAR,
    PARAMETRO_CONTROL_ELIMINAR,
    PARAMETRO_CONTROL_CONSULTAR,
    // PLANIFICACION PRODUCCION
    PLANIFICACION_PRODUCCION_REGISTRAR,
    PLANIFICACION_PRODUCCION_FINALIZAR,
    PLANIFICACION_PRODUCCION_ANULAR,
    PLANIFICACION_PRODUCCION_CONSULTAR,
    // LOTE
    LOTE_REGISTRAR,
    LOTE_ANULAR,
    LOTE_INICIAR,
    LOTE_FINALIZAR_MOLIENDA,
    LOTE_FINALIZAR_MACERACION,
    LOTE_FINALIZAR_HERVIDO,
    LOTE_FINALIZAR_FERMENTACION,
    LOTE_FINALIZAR_MADURACION,
    LOTE_FINALIZAR_ENVASADO,
    LOTE_CONSULTAR,

    // MEDICIONES DEL LOTE
    MEDICION_REGISTRAR,
    MEDICION_ANULAR,
    MEDICION_CONSULTAR,

    // CONSUMO DE INSUMOS
    CONSUMO_INSUMO_REGISTRAR,
    CONSUMO_INSUMO_ANULAR,
    CONSUMO_INSUMO_CONSULTAR,

    // ENVASADO DE LOTE
    ENVASADO_REGISTRAR,
    ENVASADO_ANULAR,
    ENVASADO_CONSULTAR,

    // BARRIL
    BARRIL_CREAR,
    BARRIL_MODIFICAR,
    BARRIL_ELIMINAR,
    BARRIL_CONSULTAR,

    // LIMPIEZA EQUIPAMIENTO
    LIMPIEZA_EQUIPAMIENTO_REGISTRAR,
    LIMPIEZA_EQUIPAMIENTO_ANULAR,
    LIMPIEZA_EQUIPAMIENTO_CONSULTAR,

    // PRESENTACION COMERCIAL
    PRESENTACION_COMERCIAL_CREAR,
    PRESENTACION_COMERCIAL_MODIFICAR,
    PRESENTACION_COMERCIAL_ELIMINAR,
    PRESENTACION_COMERCIAL_CONSULTAR,

    // PAIS
    PAIS_CREAR,
    PAIS_MODIFICAR,
    PAIS_ELIMINAR,
    PAIS_CONSULTAR,

    // PROVINCIA
    PROVINCIA_CREAR,
    PROVINCIA_MODIFICAR,
    PROVINCIA_ELIMINAR,
    PROVINCIA_CONSULTAR,

    // LOCALIDAD
    LOCALIDAD_CREAR,
    LOCALIDAD_MODIFICAR,
    LOCALIDAD_ELIMINAR,
    LOCALIDAD_CONSULTAR,

    // PROVEEDOR
    PROVEEDOR_CREAR,
    PROVEEDOR_MODIFICAR,
    PROVEEDOR_ELIMINAR,
    PROVEEDOR_CONSULTAR,

    // ORDEN DE COMPRA
    ORDEN_COMPRA_REGISTRAR,
    ORDEN_COMPRA_FINALIZAR,
    ORDEN_COMPRA_ANULAR,
    ORDEN_COMPRA_CONSULTAR,

    // INGRESO DE INSUMO
    INGRESO_INSUMO_REGISTRAR,
    INGRESO_INSUMO_ANULAR,
    INGRESO_INSUMO_CONSULTAR,

    // COSTO DIRECTO ADICIONAL
    COSTO_DIRECTO_ADICIONAL_CREAR,
    COSTO_DIRECTO_ADICIONAL_MODIFICAR,
    COSTO_DIRECTO_ADICIONAL_ELIMINAR,
    COSTO_DIRECTO_ADICIONAL_CONSULTAR,

    // COSTO FIJO
    COSTO_FIJO_CREAR,
    COSTO_FIJO_MODIFICAR,
    COSTO_FIJO_ELIMINAR,
    COSTO_FIJO_CONSULTAR,

    // CLIENTE
    CLIENTE_CREAR,
    CLIENTE_MODIFICAR,
    CLIENTE_ELIMINAR,
    CLIENTE_CONSULTAR,

    // DESPACHO BARRIL
    DESPACHO_BARRIL_REGISTRAR,
    DESPACHO_BARRIL_ANULAR,
    DESPACHO_BARRIL_CONSULTAR,

    // DEVOLUCION BARRIL
    DEVOLUCION_BARRIL_REGISTRAR,
    DEVOLUCION_BARRIL_ANULAR,
    DEVOLUCION_BARRIL_CONSULTAR,

    // FRACCIONAMIENTO DE BARRIL
    FRACCIONAMIENTO_BARRIL_REGISTRAR,
    FRACCIONAMIENTO_BARRIL_ANULAR,
    FRACCIONAMIENTO_BARRIL_CONSULTAR,

    // USUARIO
    USUARIO_CREAR,
    USUARIO_MODIFICAR,
    USUARIO_ELIMINAR,
    USUARIO_CONSULTAR,

    // LIMPIEZA BARRIL
    LIMPIEZA_BARRIL_REGISTRAR,
    LIMPIEZA_BARRIL_ANULAR,
    LIMPIEZA_BARRIL_CONSULTAR,

    // MOTIVO AJUSTE
    MOTIVO_AJUSTE_CREAR,
    MOTIVO_AJUSTE_MODIFICAR,
    MOTIVO_AJUSTE_ELIMINAR,
    MOTIVO_AJUSTE_CONSULTAR,

    // AJUSTE DE STOCK
    AJUSTE_STOCK_REGISTRAR,
    AJUSTE_STOCK_ANULAR,
    AJUSTE_STOCK_CONSULTAR,

    // MANTENIMIENTO DE EQUIPAMIENTO
    MANTENIMIENTO_EQUIPAMIENTO_REGISTRAR,
    MANTENIMIENTO_EQUIPAMIENTO_ANULAR,
    MANTENIMIENTO_EQUIPAMIENTO_CONSULTAR,
}
